# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f2599d216a97e25129ef73dfaa872fdc3912005a8f9349aabf56ba3c01008a1d9d76585449c059dcd01a1ad8ab7f6629cb2864873b15218c3da4bae88000c6

test:
  secret_key_base: efdd8d88d40be506b3df7c50dc837508dd4f014e9c00c7d93acce5503f1aafc5b63190a11f833ccf5738211683b5515df4e8473c0cbffd0404ec88808bba6802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
